apiVersion: v1
kind: Secret
metadata:
  name: hello-app-db-secret
stringData:
  POSTGRES_CONNECTION_STRING: Server=poc-postgres.cd4w0s8y0rxk.us-west-1.rds.amazonaws.com;5432;User=appuser;Database=appdb;SsL=verifyFull;
