apiVersion: v1
kind: Secret
metadata:
  name: hello-app-db-secret
stringData:
  POSTGRES_CONNECTION_STRING: Server=poc-postgres.ck942i80w25j.us-east-1.rds.amazonaws.com;5432;User=appuser;Database=appdb;SsL=verifyFull;
