apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: aiml-audio-gateway
  namespace: default
  annotations:
    kustomize.config.k8s.io/needs-hash: "true"
    needs-argocd-vault-plugin: true
type: Opaque
stringData:
  CLIENT_SECRET: <path:/stack/dev-az-westus-mongoose/workload/aiml-audio-gateway/CLIENT_SECRET#secret#349865b5-f8e6-43b2-b09f-b13cc87feef3>
  MATRIX_CLIENT_CERTIFICATE_PASSWORD: <path:/service/dev-seismic/matrix_certificate_passphrase#secret#63fbaac4-8ce9-42be-80d9-53a273174898>
  NEW_RELIC_LICENSE_KEY: <path:/service/dev-seismic/new_relic_license_key#secret#2a3aafec-b748-4bb6-b838-8c5229d32542>