apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
configMapGenerator:
  - name: hello-app
    behavior: merge
    literals:
      - APP_ENV="dev"
patches:
  - path: deployment_workload_patch.yaml
